# Generated by Django 4.1.8 on 2023-04-11 09:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("todos", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="todo",
            name="date",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
